# Generated by Django 4.2 on 2023-05-03 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0002_alter_math_operation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='math',
            options={'ordering': ['-id']},
        ),
    ]
